[package]
name = "scheduleflow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7" }
crossterm = "0.27.0"
icalendar = "0.15.8"
serde = { version = "1.0.193", features = ["derive"] }
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
time = "0.3.30"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }

[dependencies.ratatui]
version = "0.24.0"
features = ["widget-calendar"]
