[package]
name = "scheduleflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7" }
crossterm = "0.27.0"
icalendar = "0.15.8"
ratatui = "0.24.0"
