[package]
name = "scheduleflow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7" }
crossterm = "0.27.0"
icalendar = "0.15.8"
time = "0.3.30"

[dependencies.ratatui]
version = "0.24.0"
features = ["widget-calendar"]
