[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
dotenv = "0.15.0"
ratatui = "0.29.0"
serde = "1.0.217"

shared = { path = "../shared" }
