use color_eyre::eyre::Result;
use crossterm::event::KeyCode;
use ratatui::{
    layout::Rect,
    widgets::{Block, Borders},
    Frame,
};

use crate::ui::tui::Cmd;

use super::screen::Screen;

#[derive(Clone)]
pub(crate) struct SignupScreen;

impl SignupScreen {
    pub(crate) fn new() -> Self {
        Self {}
    }
}

impl Screen for SignupScreen {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn render(&self, f: &mut Frame, bounds: Rect) -> Result<()> {
        let block = Block::new()
            .title(" Inner content generated by page ")
            .borders(Borders::all());

        f.render_widget(block, bounds);

        Ok(())
    }

    fn handle_input(&mut self, key: KeyCode) -> Cmd {
        todo!()
    }

    fn handle_cmd(&mut self, key: KeyCode) -> Cmd {
        todo!()
    }
}
