use ratatui::{
    layout::Rect,
    widgets::{Block, Borders},
    Frame,
};

pub(crate) struct SignupScreen;

impl SignupScreen {
    pub(crate) fn render(f: &mut Frame, bounds: Rect) {
        let block = Block::new()
            .title(" Inner content generated by page ")
            .borders(Borders::all());

        f.render_widget(block, bounds);
    }
}
